name: 部署到 EC2（含 SAST & DAST）

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  sast:
    name: SAST 扫描
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装依赖
        run: npm ci

      - name: 下载 OWASP Dependency Check
        run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
          unzip dependency-check-12.1.1-release.zip

      - name: 运行 SAST 扫描
        run: |
          dependency-check/bin/dependency-check.sh \
            --project "hdbpilot-admin" \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --out . \
            --scan .

      - name: 上传 SAST 报告
        uses: actions/upload-artifact@v4
        with:
          name: sast-report-${{ env.VERSION_TAG }}
          path: ./dependency-check-report.html

  dast:
    name: DAST 扫描
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 创建 ZAP 扫描脚本
        run: |
          echo '#!/bin/bash
          docker pull zaproxy/zap-stable
          docker run -i zaproxy/zap-stable zap-baseline.py \
            -t "https://your-frontend-url.com" \
            -l PASS > zap_baseline_report.html
          ' > zap-script.sh
          chmod +x zap-script.sh

      - name: 运行 DAST 扫描
        run: ./zap-script.sh

      - name: 上传 DAST 报告
        uses: actions/upload-artifact@v4
        with:
          name: dast-report-${{ env.VERSION_TAG }}
          path: ./zap_baseline_report.html

  ci:
    name: 构建与打包
    runs-on: ubuntu-latest
    needs: [sast, dast]
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 代码检查
        run: npm run lint

      - name: 构建项目
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.EC2_HOST }}

      - name: 创建部署包
        run: |
          tar -czf deploy.tar.gz \
            .next \
            public \
            package.json \
            package-lock.json \
            next.config.ts \
            ecosystem.config.js

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: deploy.tar.gz

  deploy:
    name: 部署到 EC2
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .

      - name: 初始化部署目录
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            sudo mkdir -p /var/www/hdbpilot-admin/releases
            sudo mkdir -p /var/www/hdbpilot-admin/shared
            sudo chown -R $USER:$USER /var/www/hdbpilot-admin
            if [ -L "/var/www/hdbpilot-admin/current" ]; then
              rm /var/www/hdbpilot-admin/current
            fi

      - name: 上传构建文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          source: "deploy.tar.gz"
          target: "/var/www/hdbpilot-admin/"

      - name: 解压并启动服务
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            set -e
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            NEW_RELEASE="/var/www/hdbpilot-admin/releases/$TIMESTAMP"
            mkdir -p "$NEW_RELEASE"
            tar -xzf deploy.tar.gz -C "$NEW_RELEASE" --strip-components=0
            cd "$NEW_RELEASE"
            [ ! -f "package-lock.json" ] && npm install --package-lock-only
            npm install --production
            cd /var/www/hdbpilot-admin
            mkdir -p shared/logs
            rm -f current
            ln -sf "releases/$TIMESTAMP" current
            pm2 stop hdbpilot-admin 2>/dev/null || true
            pm2 delete hdbpilot-admin 2>/dev/null || true
            pm2 start current/ecosystem.config.js
            pm2 save
            sudo nginx -t && sudo systemctl reload nginx
            cd releases && ls -t | tail -n +6 | xargs -I {} rm -rf {}
            cd /var/www/hdbpilot-admin && rm -f deploy.tar.gz

      - name: 健康检查
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            sleep 10
            if pm2 show hdbpilot-admin | grep -q "online"; then
              echo "✅ 应用部署成功，服务正在运行"
            else
              echo "❌ 应用部署失败"
              pm2 logs hdbpilot-admin --lines 20
              exit 1
            fi
            if sudo systemctl is-active nginx | grep -q "active"; then
              echo "✅ Nginx 服务正常"
            else
              echo "❌ Nginx 服务异常"
              exit 1
            fi
