name: Deploy to EC2 (with SAST & DAST)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION_TAG: ${{ github.run_number }}-${{ github.sha }}

jobs:
  sast:
    name: SAST Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: ESLint Security Scan
        run: npx eslint . --max-warnings=0 --format html --output-file ./eslint-report.html || true

      - name: Upload ESLint Report
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report-${{ env.VERSION_TAG }}
          path: ./eslint-report.html

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
          unzip dependency-check-12.1.1-release.zip

      - name: Run SAST Scan
        run: |
          dependency-check/bin/dependency-check.sh \
            --project "hdbpilot-admin" \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --out . \
            --scan .

      - name: Upload SAST Report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report-${{ env.VERSION_TAG }}
          path: ./dependency-check-report.html
  
  ci:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: [sast]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.EC2_HOST }}

      - name: Create deployment package
        run: |
          tar -czf deploy.tar.gz \
            .next \
            public \
            package.json \
            package-lock.json \
            next.config.ts \
            ecosystem.config.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: deploy.tar.gz

  deploy:
    name: deploy to ec2
    needs: ci
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: .

      - name: Initialize deployment directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Create application directories
            sudo mkdir -p /var/www/hdbpilot-admin/releases
            sudo mkdir -p /var/www/hdbpilot-admin/shared
            sudo chown -R $USER:$USER /var/www/hdbpilot-admin

            # Backup current version (remove symlink if it exists, will recreate later)
            if [ -L "/var/www/hdbpilot-admin/current" ]; then
              rm /var/www/hdbpilot-admin/current
            fi

      - name: Upload build files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          source: "deploy.tar.gz"
          target: "/var/www/hdbpilot-admin/"

      - name: Extract and start service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            set -e
            echo "=== Starting Deployment ==="

            # Go to application directory
            cd /var/www/hdbpilot-admin
            pwd
            ls -la

            # Create timestamp and directory
            TIMESTAMP=$(date +%Y%m%d-%H%M%S)
            echo "Timestamp: $TIMESTAMP"

            # Ensure releases directory exists
            echo "Creating releases directory..."
            mkdir -p releases

            # Create new release directory with full path
            NEW_RELEASE="/var/www/hdbpilot-admin/releases/$TIMESTAMP"
            echo "Creating new release directory: $NEW_RELEASE"
            mkdir -p "$NEW_RELEASE"

            # Verify directory creation
            if [ ! -d "$NEW_RELEASE" ]; then
              echo "Error: Failed to create directory $NEW_RELEASE"
              exit 1
            fi

            # Extract files
            echo "Extracting deployment files to: $NEW_RELEASE"
            tar -xzf deploy.tar.gz -C "$NEW_RELEASE" --strip-components=0

            # Enter new release directory
            cd "$NEW_RELEASE"
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la

            # Check required files
            if [ ! -f "package.json" ]; then
              echo "Error: package.json file not found"
              exit 1
            fi

            # Handle package-lock.json
            if [ ! -f "package-lock.json" ]; then
              echo "Generating package-lock.json..."
              npm install --package-lock-only
            fi

            # Install production dependencies
            echo "Installing production dependencies..."
            npm install --production

            # Go back to application root
            cd /var/www/hdbpilot-admin

            # Create logs directory
            echo "Creating logs directory..."
            mkdir -p shared/logs

            # Create symlink
            echo "Creating symlink..."
            rm -f current
            ln -sf "releases/$TIMESTAMP" current

            # Verify symlink
            if [ ! -L "current" ]; then
              echo "Error: Failed to create symlink"
              exit 1
            fi

            # PM2 management
            echo "Managing PM2 process..."
            pm2 stop hdbpilot-admin 2>/dev/null || echo "No running process found"
            pm2 delete hdbpilot-admin 2>/dev/null || echo "No process to delete"

            # Start application
            echo "Starting new application..."
            if [ -f "current/ecosystem.config.js" ]; then
              pm2 start current/ecosystem.config.js
              pm2 save
            else
              echo "Error: ecosystem.config.js file not found"
              exit 1
            fi

            # Check nginx and reload
            echo "Reloading nginx..."
            sudo nginx -t && sudo systemctl reload nginx

            # Cleanup
            echo "Cleaning up old releases and deployment file..."
            cd releases && ls -t | tail -n +6 | xargs -I {} rm -rf {} 2>/dev/null || true
            cd /var/www/hdbpilot-admin && rm -f deploy.tar.gz

            echo "=== Deployment Completed ==="

      - name: Health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || 22 }}
          script: |
            # Wait for the service to start
            sleep 10

            # Check service status
            if pm2 show hdbpilot-admin | grep -q "online"; then
              echo "✅ Application deployed successfully and is running"
            else
              echo "❌ Deployment failed, service not running"
              pm2 logs hdbpilot-admin --lines 20
              exit 1
            fi

            # Check nginx status
            if sudo systemctl is-active nginx | grep -q "active"; then
              echo "✅ Nginx service is active"
            else
              echo "❌ Nginx service is inactive"
              exit 1
            fi

  dast:
    name: DAST Scanning
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZAP Scan Script
        run: |
          echo '#!/bin/bash
          docker pull zaproxy/zap-stable
          docker run -i zaproxy/zap-stable zap-baseline.py \
            -t "http://18.138.231.229/" \
            -l PASS > zap_baseline_report.html
          ' > zap-script.sh
          chmod +x zap-script.sh

      - name: Run DAST Scan (non-blocking)
        run: |
          set +e
          ./zap-script.sh
          EXIT_CODE=$?
          echo "ZAP scan exited with code $EXIT_CODE"
          echo "ZAP scan completed, continuing pipeline regardless of exit code."
          set -e

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report-${{ env.VERSION_TAG }}
          path: ./zap_baseline_report.html